# Generated by Django 5.2.1 on 2025-05-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_code_expires_at',
        ),
    ]
