# Generated by Django 5.2.3 on 2025-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Password Reset Code Expiry'),
        ),
    ]
