# Generated by Django 5.2.3 on 2025-06-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0004_alter_location_description_locationreview'),
        ('adoleserbackend', '0004_user_password_reset_code_and_more'),
    ]

    operations = [
    ]
