# Generated by Django 5.2.3 on 2025-06-30 01:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0005_merge_20250629_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1023)),
                ('nota', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('horario', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoleserbackend.location')),
            ],
        ),
    ]
