# Generated by Django 5.2.3 on 2025-06-30 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0006_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='horario',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
    ]
