# Generated by Django 4.2.21 on 2025-08-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0008_alter_locationreview_user_activityreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='nota',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='nota',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
