# Generated by Django 4.2.21 on 2025-08-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0009_alter_activity_nota_alter_location_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SUPER', 'Super')], default='USER', max_length=10, verbose_name='Role'),
        ),
    ]
