# Generated by Django 4.2.21 on 2025-09-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0010_activity_created_by_location_created_by'),
        ('adoleserbackend', '0010_alter_user_role'),
        ('adoleserbackend', '0010_location_address_location_latitude_and_more'),
    ]

    operations = [
    ]
