# Generated by Django 4.2.21 on 2026-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoleserbackend', '0012_category_activity_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para contato'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / Whatsapp'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_socialnetwork',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rede Social'),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_mode',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
