# Generated by Django 5.0.1 on 2024-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSaude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localatendimento',
            name='imagens',
            field=models.ManyToManyField(blank=True, related_name='locais', to='AppSaude.imagem'),
        ),
    ]
